apiVersion: apps/v1
kind: Deployment
metadata:
  name: Budget-App
  labels:
    app: Budget-App
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Budget-App
  template:
    metadata:
      labels:
        app: Budget-App
    spec:
      containers:
      - name: Budget-App
        image: ajjurathod1998/makerable
        ports:
        - containerPort: 80
