---
version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    command: rails server -b 0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db
volumes:
  db-data: null
