---
version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    DB_HOST: db
    
volumes:
  db-data: null
