apiVersion: v1
kind: Service
metadata:
  name: Budget-App
  labels:
    app: Budget-App
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: Budget-App
